#ifndef _EKA_HW_EXPECTED_VERSION_H_
#define _EKA_HW_EXPECTED_VERSION_H_

#define EKA_EXPECTED_EPM_VERSION       0x6
#define EKA_EXPECTED_DMA_VERSION       0x1
#define EKA_EXPECTED_SNIFFER_VERSION   0x3
#define EKA_EXPECTED_SN_DRIVER_VERSION 0x4

#endif
