# CMake generated Testfile for 
# Source directory: /home/vitaly/libeka_git/libeka/cereal/unittests
# Build directory: /home/vitaly/libeka_git/libeka/cereal/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_array "/home/vitaly/libeka_git/libeka/cereal/unittests/test_array")
set_tests_properties(test_array PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_atomic "/home/vitaly/libeka_git/libeka/cereal/unittests/test_atomic")
set_tests_properties(test_atomic PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_basic_string "/home/vitaly/libeka_git/libeka/cereal/unittests/test_basic_string")
set_tests_properties(test_basic_string PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_bitset "/home/vitaly/libeka_git/libeka/cereal/unittests/test_bitset")
set_tests_properties(test_bitset PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_chrono "/home/vitaly/libeka_git/libeka/cereal/unittests/test_chrono")
set_tests_properties(test_chrono PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_complex "/home/vitaly/libeka_git/libeka/cereal/unittests/test_complex")
set_tests_properties(test_complex PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_defer "/home/vitaly/libeka_git/libeka/cereal/unittests/test_defer")
set_tests_properties(test_defer PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_deque "/home/vitaly/libeka_git/libeka/cereal/unittests/test_deque")
set_tests_properties(test_deque PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_forward_list "/home/vitaly/libeka_git/libeka/cereal/unittests/test_forward_list")
set_tests_properties(test_forward_list PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_list "/home/vitaly/libeka_git/libeka/cereal/unittests/test_list")
set_tests_properties(test_list PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_load_construct "/home/vitaly/libeka_git/libeka/cereal/unittests/test_load_construct")
set_tests_properties(test_load_construct PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_map "/home/vitaly/libeka_git/libeka/cereal/unittests/test_map")
set_tests_properties(test_map PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_memory "/home/vitaly/libeka_git/libeka/cereal/unittests/test_memory")
set_tests_properties(test_memory PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_memory_cycles "/home/vitaly/libeka_git/libeka/cereal/unittests/test_memory_cycles")
set_tests_properties(test_memory_cycles PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_multimap "/home/vitaly/libeka_git/libeka/cereal/unittests/test_multimap")
set_tests_properties(test_multimap PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_multiset "/home/vitaly/libeka_git/libeka/cereal/unittests/test_multiset")
set_tests_properties(test_multiset PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_pair "/home/vitaly/libeka_git/libeka/cereal/unittests/test_pair")
set_tests_properties(test_pair PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_pod "/home/vitaly/libeka_git/libeka/cereal/unittests/test_pod")
set_tests_properties(test_pod PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_polymorphic "/home/vitaly/libeka_git/libeka/cereal/unittests/test_polymorphic")
set_tests_properties(test_polymorphic PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_portable_binary_archive "/home/vitaly/libeka_git/libeka/cereal/unittests/test_portable_binary_archive")
set_tests_properties(test_portable_binary_archive PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_priority_queue "/home/vitaly/libeka_git/libeka/cereal/unittests/test_priority_queue")
set_tests_properties(test_priority_queue PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_queue "/home/vitaly/libeka_git/libeka/cereal/unittests/test_queue")
set_tests_properties(test_queue PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_set "/home/vitaly/libeka_git/libeka/cereal/unittests/test_set")
set_tests_properties(test_set PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_stack "/home/vitaly/libeka_git/libeka/cereal/unittests/test_stack")
set_tests_properties(test_stack PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_structs "/home/vitaly/libeka_git/libeka/cereal/unittests/test_structs")
set_tests_properties(test_structs PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_structs_minimal "/home/vitaly/libeka_git/libeka/cereal/unittests/test_structs_minimal")
set_tests_properties(test_structs_minimal PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_structs_specialized "/home/vitaly/libeka_git/libeka/cereal/unittests/test_structs_specialized")
set_tests_properties(test_structs_specialized PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_tuple "/home/vitaly/libeka_git/libeka/cereal/unittests/test_tuple")
set_tests_properties(test_tuple PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_unordered_loads "/home/vitaly/libeka_git/libeka/cereal/unittests/test_unordered_loads")
set_tests_properties(test_unordered_loads PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_unordered_map "/home/vitaly/libeka_git/libeka/cereal/unittests/test_unordered_map")
set_tests_properties(test_unordered_map PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_unordered_multimap "/home/vitaly/libeka_git/libeka/cereal/unittests/test_unordered_multimap")
set_tests_properties(test_unordered_multimap PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_unordered_multiset "/home/vitaly/libeka_git/libeka/cereal/unittests/test_unordered_multiset")
set_tests_properties(test_unordered_multiset PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_unordered_set "/home/vitaly/libeka_git/libeka/cereal/unittests/test_unordered_set")
set_tests_properties(test_unordered_set PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_user_data_adapters "/home/vitaly/libeka_git/libeka/cereal/unittests/test_user_data_adapters")
set_tests_properties(test_user_data_adapters PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_valarray "/home/vitaly/libeka_git/libeka/cereal/unittests/test_valarray")
set_tests_properties(test_valarray PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_vector "/home/vitaly/libeka_git/libeka/cereal/unittests/test_vector")
set_tests_properties(test_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_versioning "/home/vitaly/libeka_git/libeka/cereal/unittests/test_versioning")
set_tests_properties(test_versioning PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;48;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
add_test(test_cmake_config_module "/usr/bin/cmake3" "-P" "/home/vitaly/libeka_git/libeka/cereal/unittests/cmake-config-module.cmake")
set_tests_properties(test_cmake_config_module PROPERTIES  _BACKTRACE_TRIPLES "/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;103;add_test;/home/vitaly/libeka_git/libeka/cereal/unittests/CMakeLists.txt;0;")
subdirs("boost")
